"use strict";
const { 
    blue, 
    blueBright,
    red,
    redBright,
    green,
    greenBright,
    magenta,
    magentaBright,
    yellow,
    yellowBright,
    bgBlue,
    bgBlueBright,
    bgGreen,
    bgGreenBright,
    bgYellow,
    bgYellowBright,
} = require( 'chalk' ).default;
module.exports = {
    blue,
    blueBright,
    red,
    redBright,
    green,
    greenBright,
    magenta,
    magentaBright,
    yellow,
    yellowBright,
    bgBlue,
    bgBlueBright,
    bgGreen,
    bgGreenBright,
    bgYellow,
    bgYellowBright,
}